[build]
  # Tell Netlify to "walk" into these folders to find your site
  base = "data/oceanleans_website"
  # Once inside oceanleans_website, the site is right here (.)
  publish = "."
  # Once inside oceanleans_website, the functions are here
  [build]
  functions = "website/data/oceanleans-website/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.scdn.co;"